services:
  insadb:
    image: postgres:15
    container_name: station_${ENV}_postgres
    env_file: .env
    ports:
      - "${HOST_POSTGRES_PORT:-5432}:5432"
    volumes:
      - station_postgres_data:/var/lib/postgresql/data
    networks:
      - station_orc_net
    restart: always

  redis:
    image: redis:7
    container_name: station_${ENV}_redis
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1"]
    ports:
      - "${HOST_REDIS_PORT:-6379}:6379"
    volumes:
      - station_redis_data:/data
    networks:
      - station_orc_net
    restart: always

  django_server:
    build: .
    container_name: station_${ENV}_django
    env_file: .env
    volumes:
      - .:/app
      - ./media:/app/media
      - ./staticfiles:/app/staticfiles
      - ./static:/app/static
    ports:
      - "${HOST_DJANGO_PORT:-8000}:8000"
    depends_on:
      - insadb
      - redis
    networks:
      - station_orc_net
    restart: always

  celery_worker:
    build: .
    container_name: station_${ENV}_celery_worker
    env_file: .env
    command: celery -A InsaBackednLatest worker -l info --concurrency=2 --max-tasks-per-child=50
    depends_on:
      - redis
      - insadb
      - django_server
    volumes:
      - .:/app
    networks:
      - station_orc_net
    restart: always

  celery_beat:
    build: .
    container_name: station_${ENV}_celery_beat
    env_file: .env
    command: >
      sh -c "
      echo 'Waiting for database to be ready...' &&
      until python manage.py migrate --check > /dev/null 2>&1; do
        echo 'Database not ready or migrations not applied, retrying in 5s...' &&
        sleep 5;
      done &&
      echo 'Starting Celery Beat...' &&
      celery -A InsaBackednLatest beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
      "
    depends_on:
      - redis
      - insadb
      - django_server
    volumes:
      - .:/app
    networks:
      - station_orc_net
    restart: always

volumes:
  station_postgres_data:
  station_redis_data:

networks:
  station_orc_net:
    external: true
