services:
  insadb:
    image: postgres:15
    container_name: dengego_postgres_primary
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - dengego_postgres_data:/var/lib/postgresql/data
    networks:
      - dengego_orc_net
    restart: always
  django_server:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8002:8000"
    depends_on:
      - insadb
    networks:
      - dengego_orc_net
    restart: always

volumes:
  dengego_postgres_data:
networks:
  dengego_orc_net:
    external: true
